<SplashScreen>:
    id: splash
    FloatLayout:
        Image:
            source: 'imagens/logo1.png' # caminho
            size_hint: 0.5, 0.6 # tamanho em 50%
            pos_hint: {'center_x': 0.5, 'center_y': 0.6}
 
        Label:
            text: 'Desenvolvido por T98 © 2024'
            font_size: '16sp'
            color: 1, 0, 0, 1
            font_name: "MinhaFonte"
            pos_hint: {'center_x': 0.5, 'y': -0.02}